export const initialCards = [
  {
    id: 1,
    name: 'Mario',
    imageSrc: 'src/assets/cards/mario.png',
    flipped: false,
    matched: false,
  },
  {
    id: 1,
    name: 'Mario',
    imageSrc: 'src/assets/cards/mario.png',
    flipped: false,
    matched: false,
  },
  {
    id: 2,
    name: 'Luigi',
    imageSrc: 'src/assets/cards/luigi.png',
    flipped: false,
    matched: false,
  },
  {
    id: 2,
    name: 'Luigi',
    imageSrc: 'src/assets/cards/luigi.png',
    flipped: false,
    matched: false,
  },
  {
    id: 3,
    name: 'Baby Mario',
    imageSrc: 'src/assets/cards/baby-mario.png',
    flipped: false,
    matched: false,
  },
  {
    id: 3,
    name: 'Baby Mario',
    imageSrc: 'src/assets/cards/baby-mario.png',
    flipped: false,
    matched: false,
  },
  {
    id: 4,
    name: 'Baby Luigi',
    imageSrc: 'src/assets/cards/baby-luigi.png',
    flipped: false,
    matched: false,
  },
  {
    id: 4,
    name: 'Baby Luigi',
    imageSrc: 'src/assets/cards/baby-luigi.png',
    flipped: false,
    matched: false,
  },
  {
    id: 5,
    name: 'Boo',
    imageSrc: 'src/assets/cards/boo.png',
    flipped: false,
    matched: false,
  },
  {
    id: 5,
    name: 'Boo',
    imageSrc: 'src/assets/cards/boo.png',
    flipped: false,
    matched: false,
  },
  {
    id: 6,
    name: 'Bowser',
    imageSrc: 'src/assets/cards/bowser.png',
    flipped: false,
    matched: false,
  },
  {
    id: 6,
    name: 'Bowser',
    imageSrc: 'src/assets/cards/bowser.png',
    flipped: false,
    matched: false,
  },
  {
    id: 7,
    name: 'Bowser Jr.',
    imageSrc: 'src/assets/cards/bowser-jr.png',
    flipped: false,
    matched: false,
  },
  {
    id: 7,
    name: 'Bowser Jr.',
    imageSrc: 'src/assets/cards/bowser-jr.png',
    flipped: false,
    matched: false,
  },
  {
    id: 8,
    name: 'Daisy',
    imageSrc: 'src/assets/cards/daisy.png',
    flipped: false,
    matched: false,
  },
  {
    id: 8,
    name: 'Daisy',
    imageSrc: 'src/assets/cards/daisy.png',
    flipped: false,
    matched: false,
  },
  {
    id: 10,
    name: 'Donkey Kong',
    imageSrc: 'src/assets/cards/donkey-kong.png',
    flipped: false,
    matched: false,
  },
  {
    id: 10,
    name: 'Donkey Kong',
    imageSrc: 'src/assets/cards/donkey-kong.png',
    flipped: false,
    matched: false,
  },
  {
    id: 11,
    name: 'Koopa Troopa',
    imageSrc: 'src/assets/cards/koopa-troopa.png',
    flipped: false,
    matched: false,
  },
  {
    id: 11,
    name: 'Koopa Troopa',
    imageSrc: 'src/assets/cards/koopa-troopa.png',
    flipped: false,
    matched: false,
  },
  {
    id: 12,
    name: 'Peach',
    imageSrc: 'src/assets/cards/peach.png',
    flipped: false,
    matched: false,
  },
  {
    id: 12,
    name: 'Peach',
    imageSrc: 'src/assets/cards/peach.png',
    flipped: false,
    matched: false,
  },
  {
    id: 13,
    name: 'Toad',
    imageSrc: 'src/assets/cards/toad.png',
    flipped: false,
    matched: false,
  },
  {
    id: 13,
    name: 'Toad',
    imageSrc: 'src/assets/cards/toad.png',
    flipped: false,
    matched: false,
  },
  {
    id: 14,
    name: 'Waluigi',
    imageSrc: 'src/assets/cards/waluigi.png',
    flipped: false,
    matched: false,
  },
  {
    id: 14,
    name: 'Waluigi',
    imageSrc: 'src/assets/cards/waluigi.png',
    flipped: false,
    matched: false,
  },
  {
    id: 15,
    name: 'Wario',
    imageSrc: 'src/assets/cards/wario.png',
    flipped: false,
    matched: false,
  },
  {
    id: 15,
    name: 'Wario',
    imageSrc: 'src/assets/cards/wario.png',
    flipped: false,
    matched: false,
  },
  {
    id: 16,
    name: 'Yoshi',
    imageSrc: 'src/assets/cards/yoshi.png',
    flipped: false,
    matched: false,
  },
  {
    id: 16,
    name: 'Yoshi',
    imageSrc: 'src/assets/cards/yoshi.png',
    flipped: false,
    matched: false,
  },
];

export function shuffle(array) {
  // Fisher-Yates shuffle algorithm implementation
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}
